package indexer

import (
	"encoding/json"
	"fmt"
	"strings"
	"testing"

	"github.com/stellar/go/xdr"
)

func TestScValToJSON(t *testing.T) {
	str := "AAAAEwAAAAEAAAABAAAAAwAAAA8AAAAITUVUQURBVEEAAAARAAAAAQAAAAMAAAAPAAAAB2RlY2ltYWwAAAAAAwAAAAcAAAAPAAAABG5hbWUAAAAOAAAAOlo6R0M2SExZMkpYS1hZWFVVM1hZQzYzTzJSSk5INEUzR0VXMjZBQlRIREY2QUY2TVkzMkI1UVJJU08AAAAAAA8AAAAGc3ltYm9sAAAAAAAOAAAABFoAAAAAAAAQAAAAAQAAAAEAAAAPAAAABUFkbWluAAAAAAAAEgAAAAAAAAAAvHXjSbqvi9KbvgXtu1FLT8JsxLa8AMzjL4BfMxvQewgAAAAQAAAAAQAAAAEAAAAPAAAACUFzc2V0SW5mbwAAAAAAABAAAAABAAAAAgAAAA8AAAAJQWxwaGFOdW00AAAAAAAAEQAAAAEAAAACAAAADwAAAAphc3NldF9jb2RlAAAAAAAOAAAABFoAAAAAAAAPAAAABmlzc3VlcgAAAAAADQAAACC8deNJuq+L0pu+Be27UUtPwmzEtrwAzOMvgF8zG9B7CA=="
	var scVal = xdr.ScVal{}
	xdr.SafeUnmarshalBase64(str, &scVal)
	data := scValToGo(scVal)
	jsonData, _ := json.Marshal(data)
	jsonString := string(jsonData)
	fmt.Println(strings.Replace(jsonString, "\\u0000", "", -1))
}
