NETWORK_PASSPHRASE="Test SDF Future Network ; October 2022"
FAILURE_SAFETY=0
UNSAFE_QUORUM=true

[[HOME_DOMAINS]]
HOME_DOMAIN="futurenet.stellar.org"
QUALITY="MEDIUM"

[[VALIDATORS]]
NAME="sdf_futurenet_1"
HOME_DOMAIN="futurenet.stellar.org"
PUBLIC_KEY="GBRIF2N52GVN3EXBBICD5F4L5VUFXK6S6VOUCF6T2DWPLOLGWEPPYZTF"
ADDRESS="core-live-futurenet.stellar.org:11625"
HISTORY="curl -sf http://history-futurenet.stellar.org/{0} -o {1}"