services:
  soroban-rpc:
    build:
      context: ../..
      dockerfile: deploy/mainnet/Dockerfile
    container_name: soroban-rpc-mainnet
    # Use .env file from project root
    env_file: ../../.env
    ports:
      - "80:80"
    environment:
      - TZ=UTC/GMT
      - POSTGRES_DSN=$POSTGRES_DSN
    volumes:
      - ./stellar-captive-core-live.toml:/app/cmd/soroban-rpc/config/stellar-captive-core-live.toml
      - soroban-data:/data
    restart: unless-stopped

  dequeue-1:
    build:
      context: ../..
      dockerfile: deploy/mainnet/Dockerfile
    container_name: soroban-dequeue-1
    env_file: ../../.env
    command: ["go", "run", "cmd/soroban-rpc/internal/indexer/queue_consumer/*.go"]
    environment:
      - TZ=UTC/GMT
      - POSTGRES_DSN=$POSTGRES_DSN
    restart: unless-stopped

  dequeue-2:
    build:
      context: ../..
      dockerfile: deploy/mainnet/Dockerfile
    container_name: soroban-dequeue-2
    env_file: ../../.env
    command: ["go", "run", "cmd/soroban-rpc/internal/indexer/queue_consumer/*.go"]
    environment:
      - TZ=UTC/GMT
      - POSTGRES_DSN=$POSTGRES_DSN
    restart: unless-stopped

  dequeue-3:
    build:
      context: ../..
      dockerfile: deploy/mainnet/Dockerfile
    container_name: soroban-dequeue-3
    env_file: ../../.env
    command: ["go", "run", "cmd/soroban-rpc/internal/indexer/queue_consumer/*.go"]
    environment:
      - TZ=UTC/GMT
      - POSTGRES_DSN=$POSTGRES_DSN
    restart: unless-stopped

  dequeue-4:
    build:
      context: ../..
      dockerfile: deploy/mainnet/Dockerfile
    container_name: soroban-dequeue-4
    env_file: ../../.env
    command: ["go", "run", "cmd/soroban-rpc/internal/indexer/queue_consumer/*.go"]
    environment:
      - TZ=UTC/GMT
      - POSTGRES_DSN=$POSTGRES_DSN
    restart: unless-stopped

  dequeue-5:
    build:
      context: ../..
      dockerfile: deploy/mainnet/Dockerfile
    container_name: soroban-dequeue-5
    env_file: ../../.env
    command: ["go", "run", "cmd/soroban-rpc/internal/indexer/queue_consumer/*.go"]
    environment:
      - TZ=UTC/GMT
      - POSTGRES_DSN=$POSTGRES_DSN
    restart: unless-stopped

volumes:
  soroban-data:
